### ISSUE TITLE
Conteo_Transectos_LagartijasEtCangrejos_Chinchorro_04Jun2018.xls

### ISSUE THREAD

**Issue by ghost** [IslasGECI/datos_en_excel#3]
En el canal de *datos* en Slack, se encuentra el archivo [`datos BCH para analisis 040618.xlsx`](https://islas.slack.com/files/U06MGBSBS/FB1GPNZEW/datos_bch_para_analisis_040618.xlsx). El nombre de este archivo no cumple con el protocolo
> Nombra tus archivos indicando, siempre en el mismo orden, el tipo de monitoreo (o simplemente la palabra Datos), variable(s), especie (o grupo), isla (o región geográfica) y fecha de última actualización. E.g. “Censo_Nidos_Albatros_Guadalupe_01Ene2018”, “Busqueda_Madrigueras_AvesMarinas_PacificoNorte_01Ene2018”, etc. Además, no uses espacios, usa guion bajo “_”.

El nombre debe tener 5 partes separadas por 4 guiones bajos. Cada parte puede usar _CamelCase_.

**Comment by evaristor** [comment]
Renombré el archivo `datos BCH para analisis 040618.xlsx` a `Conteo_Transectos_LagartijasEtCangrejos_Chinchorro_04Jun2018.xls` para seguir el protocolo

**Comment by evaristor** [comment]
Estoy en espera de cambios solicitados a CJ.

**Comment by evaristor** [comment]
https://bitbucket.org/IslasGECI/datos-texto/src/default/datapackage/Conteo_Transectos_LagartijasEtCangrejos/
