### ISSUE TITLE
monitoreo_roedores.xlsx

### ISSUE THREAD

**Issue by evaristor** [IslasGECI/datos_en_excel#4]
Verifica que cumpla con el [Protocolo para guardar datos en Excel](https://islasgeci.github.io/datos_en_excel/)

- [`monitoreo_roedores.xlsx`](https://islas.slack.com/files/U0979HT18/FB7MTJW91/monitoreo_roedores.xlsx)

**Comment by ylora** [comment]
`Tu archivo NO cumple con la convención 0.16.623 `

**Comment by evaristor** [comment]
Hay que echarle la mano... Ya sabemos que no cumple, pero hay que sentarse con él y explicarle por qué. Además, hay que ser pacientes y tolerantes porque estamos cambiando al nuevo [protocolo](https://islasgeci.github.io/datos_en_excel/) que todavía no está terminado.
